---
title: "Discussion 14"
author: "Bryan Persaud"
date: "5/4/2020"
output: html_document
---

# Chapter 8 Section 8.8 Exercise 7

In Exercises 7 – 12, find a formula for the nth term of the Taylor series of f(x), centered at c, by finding the coefficients of the first few powers of x and looking for a paƩern. (The formulas for several of these are found in Key Idea 8.8.1; show work verifying these formula.)

7. f(x) = cos x; c = π/2

Solution:

Let's take the derivative of f(x) a couple of times and set x = π/2.

f(x) = cos(x), cos(π/2) = 0
f'(x) = -sin(x), -sin(π/2) = -1
f''(x) = -cos(x), -cos(π/2) = 0
f'''(x) = sin(x), sin(π/2) = 1
f''''(x) = cos(x), cos(π/2) = 0
f'''''(x) = -sin(x), -sin(π/2) = -1
f''''''(x) = -cos(x), -cos(π/2) = 0

Notice the pattern, you get a 0 followed by alternating signs of 1. 

The Taylor Series of f(x) centered at π/2 is $\sum _{ n=0 }^{ \infty  }{ \frac { { f }^{ (n) }(\frac { \pi  }{ 2 } ) }{ n! }  } { (x-\frac { \pi  }{ 2 } ) }^{ n }$

Now we plug in the derivatives at π/2:

$\sum _{ n=0 }^{ \infty  }{ \frac { { f }^{ (n) }(\frac { \pi  }{ 2 } ) }{ n! }  } { (x-\frac { \pi  }{ 2 } ) }^{ n }$ =

${ \frac { { f }^{ (0) }(\frac { \pi  }{ 2 } ) }{ 0! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 0 }+{ \frac { { f }^{ (1) }(\frac { \pi  }{ 2 } ) }{ 1! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 1 }+{ \frac { { f }^{ (2) }(\frac { \pi  }{ 2 } ) }{ 2! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 2 }+{ \frac { { f }^{ (3) }(\frac { \pi  }{ 2 } ) }{ 3! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 3 }+{ \frac { { f }^{ (4) }(\frac { \pi  }{ 2 } ) }{ 4! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 4 }+{ \frac { { f }^{ (5) }(\frac { \pi  }{ 2 } ) }{ 5! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 5 }+{ \frac { { f }^{ (6) }(\frac { \pi  }{ 2 } ) }{ 6! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 6 }+...$ =

${ \frac { 0  }{ 0! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 0 }+{ \frac { -1 }{ 1! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 1 }+{ \frac { 0 }{ 2! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 2 }+{ \frac { 1 }{ 3! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 3 }+{ \frac { 0 }{ 4! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 4 }+{ \frac { -1 }{ 5! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 5 }+{ \frac { 0 }{ 6! }  } { (x-\frac { \pi  }{ 2 } ) }^{ 6 }+...$ =

$0- { (x-\frac { \pi  }{ 2 } ) }^{ 1 }+{ \frac { 1 }{ 6 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 3 }+0-{ \frac { 1 }{ 120 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 5 }+0+...$ =

$- { (x-\frac { \pi  }{ 2 } ) }^{ 1 }+{ \frac { 1 }{ 6 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 3 }-{ \frac { 1 }{ 120 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 5 }+...$

We can see that when n is even the term ends up equal to 0, so we are left with the terms when n is odd.

From this pattern a formula for the nth term of the Taylor Series of cos(x) centered at π/2 is $\sum _{ n=0 }^{ \infty  }{ \frac { { f }^{ (n) }(\frac { \pi  }{ 2 } ) }{ n! }  } { (x-\frac { \pi  }{ 2 } ) }^{ n }=- { (x-\frac { \pi  }{ 2 } ) }^{ 1 }+{ \frac { 1 }{ 6 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 3 }-{ \frac { 1 }{ 120 }  } { (x-\frac { \pi  }{ 2 } ) }^{ 5 }+...$

This is my attempt to simplify the formula: $\sum _{ n=0 }^{ \infty  }-{ \frac { (-1+{ (-1) }^{ n }){ (x-\frac { \pi  }{ 2 } ) }^{ n } }{ 2n! }  }$